version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: workflow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workflow
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: workflow_app
    depends_on:
      - db
    ports:
      - "5001:8080"
    environment:
      - FLASK_ENV=development

volumes:
  db_data:
